apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth

spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-auth
  template :
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
      - name: user-auth
        image: user-auth:v1
        ports:
            - containerPort: 3001

