apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shopping-cart
spec:
  serviceName: "shopping-cart"
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: shopping-cart-service:v1
        ports:
        - containerPort: 3002
        volumeMounts:
        - name: shopping-cart-data
          mountPath: /app/data
  volumeClaimTemplates:
  - metadata:
      name: shopping-cart-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
